### ISSUE TITLE
Support of "dirty" tracking

### ISSUE THREAD

**Issue by ledermann** [mbleigh/acts-as-taggable-on#1]
It would be very nice if setting the "tag_list" attribute would support the dirty tracking available in ActiveRecord since Rails 2.1:

```
my_model = MyModel.create :tag_list => 'ruby'
my_model.tag_list = 'ruby, rails'
my_model.changed? # true
my_model.tag_list_changed? # true
my_model.tag_list_change #  ["ruby", "ruby, rails"] 
my_model.changes # {"tag_list"=>["ruby", "ruby, rails"]}
```

With such an enhancement, the plugin collectiveidea/acts_as_audited could track changes of tags.

**Comment by tquill** [comment]
Got collectiveidea/audited working correctly with acts_as_taggable using the after_audit callback like this:

```
def around_audit
  current_audit = yield
  if current_audit.audited_changes.has_key?("tag_list")
    current_audit.audited_changes["tag_list"][1] = self.tag_list
    current_audit.save
  end
end
```

**Comment by augustosamame** [comment]
Hi @tquill . Looks exactly like what I need. But where do I put this code?
