### ISSUE TITLE
DEPRECATION WARNING: last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by francesco-loreti** [mbleigh/acts-as-taggable-on#1003]
acts-as-taggable-on 6.5.0
rails Rails 6.0.3.1
Ruby 2.7.1

Running specs that involve tags results in this deprecation notice:
`acts-as-taggable-on-6.5.0/lib/acts_as_taggable_on/tagging.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

**Comment by brchristian** [comment]
We are having this issue as well. Looks to me like https://github.com/mbleigh/acts-as-taggable-on/pull/999 fixed this, but it hasn’t made it into a rubygems release.

@mbleigh, any chance we could get a 6.5.1 that includes https://github.com/mbleigh/acts-as-taggable-on/pull/999 in it?

**Comment by stanhu** [comment]
@mbleigh Would you mind tagging a new release here for Ruby 2.7?

**Comment by silva96** [comment]
looking forward for this update too.

**Comment by igor-drozdov** [comment]
@seuros could you please have a look as well?

**Comment by ErCollao** [comment]
+1 to this, and thanks for making a great gem!

**Comment by spikeheap** [comment]
We're coming up against this issue as well. I'd normally not "+1" issues, but it looks about time for a monthly poke to resurface it.

Are there any plans for a release? Is this module still maintained? It looks like changes have made it into the main branch, but there's not been a release in 12 months.

**Comment by ruurd** [comment]
**+1 as well**

**Comment by seuros** [comment]
7.0.0 was released

**Comment by silva96** [comment]
👏  @seuros !

**Comment by ruurd** [comment]
Thank you @seuros and everybody!
