### ISSUE TITLE
Feature suggestion: force_titleize

### ISSUE THREAD

**Issue by mcauser** [mbleigh/acts-as-taggable-on#1011]
There is a `force_parameterize`. What about a `force_titleize` option?

**Comment by seuros** [comment]
You can write you own Parser and Swap the generic one. 
https://github.com/mbleigh/acts-as-taggable-on#tag-parsers
https://github.com/mbleigh/acts-as-taggable-on/blob/master/lib/acts_as_taggable_on/generic_parser.rb
