### ISSUE TITLE
Fix for Rails 6.1?

### ISSUE THREAD

**Issue by davidwparker** [mbleigh/acts-as-taggable-on#1016]
Getting this error:

```
ActiveRecord::RecordInvalid: Validation failed: Tagger must exist
```

Seeing this dependency in the gem:

```
  gem.add_runtime_dependency 'activerecord', '>= 5.0', '< 6.1'
```

Is there a way to upgrade this without forking? Or is a release being planned soon?

Thanks!

**Comment by mkilling** [comment]
There are three open pull requests adding Rails 6.1 support, with this one seemingly being the only one that passes CI: https://github.com/mbleigh/acts-as-taggable-on/pull/1013

Is there anybody maintaining this repository still who could merge that PR?

**Comment by GeekOnCoffee** [comment]
#1013  was merged.
