### ISSUE TITLE
Models won't save if they already have a `belongs_to :tenant` and `acts_as_taggable_tenant` is used

### ISSUE THREAD

**Issue by jbescoyez** [mbleigh/acts-as-taggable-on#1036]
# How to reproduce:

```ruby

class Tenant < ApplicationRecord
  has_many :users
end

class User < ApplicationRecord
  belongs_to :tenant
  acts_as_taggable_on :tags
  acts_as_taggable_tenant :tenant_id
end

Tenant.create!
```

# Expected behavior

The tenant is created

# Actual behavior

The following error is thrown.

```
NoMethodError - undefined method `marked_for_destruction?' for ID:Integer
```

# Investigation

This is due to: https://github.com/mbleigh/acts-as-taggable-on/pull/1000/files#diff-f3570227aa94bb5887e3cb70c6a69fb30861dbecaa1ee498153371a1e10fc314R217

This line overrides the tenant method and returns an integer instead of an object.
This can be easily fixed by namescoping the method (e.g. `taggable_tenant_id`).

cc @lunaru (BTW, thank you for your work 👍 )

**Comment by ngouy** [comment]
same here, tenant is already an existing thing in our data modelisation, the 8.0.0 breaks everything

**Comment by ngouy** [comment]
@lunaru a solution could be to rename tenants to less generic/more taggable specific term such as "taggable_tenant"

**Comment by lunaru** [comment]
@jbescoyez @ngouy namespacing this field (`taggable_tenant` and `taggable_tenant_id`) makes sense. PRs welcome!

**Comment by lunaru** [comment]
Please note that method-level changes would be preferred since that would remove the need to run a migration for the `tenant` column in the `taggings` table

**Comment by ngouy** [comment]
From a db perspective indeed we don't need any updates. Will check it out when I have time

**Comment by ngouy** [comment]
@jbescoyez once new version is out check it out and tell me if it works for you. It worked here

**Comment by ngouy** [comment]
> @jbescoyez @ngouy namespacing this field (`taggable_tenant` and `taggable_tenant_id`) makes sense. PRs welcome!

I didn't rename tenant_id since it's only internal logic, taggable models didn't inherit this attribute

**Comment by jbescoyez** [comment]
@ngouy I finally moved on without this gem. However, your PR is exactly the approach I would have taken. Tnx!
