### ISSUE TITLE
Tag does not auto destroy when tagging moves to another tag

### ISSUE THREAD

**Issue by hatu90** [mbleigh/acts-as-taggable-on#1041]
When I am doing moving tagging to another tag ( using tagging.update(tag: another_tag)), even the current tag has taggings_count to be zero, the current_tag is not deleted.

**Comment by seuros** [comment]
Why not delete the tagging and create it in another model ? 
I think you are bypassing the Activerecord callbacks

**Comment by hatu90** [comment]
Thank @seuros
