### ISSUE TITLE
I don't know how to uninstall

### ISSUE THREAD

**Issue by toshi-ue** [mbleigh/acts-as-taggable-on#1050]
I used this gem in the beginning.
However, it is no longer used as a function.
Currently there are only tables and records in the DB (it's okay to delete them).
The installation method is written, but I don't know the procedure to uninstall it.
I would like to know the procedure for uninstalling.

Thank you.

**Comment by marcelbonnet** [comment]
Try _rake db:rollback STEP=n_

**Comment by EthanReinholt2001** [comment]
Same issue
