### ISSUE TITLE
Tag queries are performed even though I'm not calling / using the tags

### ISSUE THREAD

**Issue by silva96** [mbleigh/acts-as-taggable-on#1075]
UPDATE: This is not a bug of the gem. this is caused only in the Console, with User model that includes devise authenticable module. See https://github.com/mbleigh/acts-as-taggable-on/issues/1075#issuecomment-1016706312

------------

Tag queries are performed even though I'm not calling / using the tags, for example:

```ruby
irb(main):001:0> User.last
  User Load (0.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ActsAsTaggableOn::Tagging Load (0.5ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2  [["taggable_id", 83632], ["taggable_type", "User"]]
  ActsAsTaggableOn::Tag Load (0.6ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2 AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)
  ```
  
  I don't use the tags everywhere I initialize a user, but it still queries the tags.
  
  I would expect the queries be fired whenever I use something related the tags, like:
  
  ```ruby
  user = User.last
  tags = user.tag_list.join(' ,')
  ```
  
  Adding a cache (`cached_tag_list`)  reduces one query
  
  ```ruby
  irb(main):001:0> User.last
  User Load (0.9ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ActsAsTaggableOn::Tagging Load (0.8ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2  [["taggable_id", 83632], ["taggable_type", "User"]]
```

What is weird is that I also have a `Post` model that has the same cache and tag column name

```ruby
acts_as_taggable_on :tags
```

and it does not make a query

```ruby
  irb(main):001:0> Post.last
  Post Load (0.9ms)  SELECT "posts".* FROM "posts" ORDER BY "posts"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ```

**Comment by silva96** [comment]
Found the culprit, 

User class is using `devise`

```ruby
devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :trackable
```

Still investigating the reason why adding device fires the queries.

**Comment by niuage** [comment]
Thanks a lot for that, wasnt easy to find I bet.
