### ISSUE TITLE
How to get a list of all tags, but only for one context?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [mbleigh/acts-as-taggable-on#1085]
As the title says, we have multiple models with mutliple contexts..

How can I get a list of all unique tag names, but only for one context? In the readme there is no example and I couldn't find a solution?

**Comment by veritas1** [comment]
There is a `for_context` method on the `Tag` class, e.g `ActsAsTaggableOn::Tag.for_context(:tags)` or `ActsAsTaggableOn::Tag.for_context(:skills)` etc

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you so much, I added a PR to update the Readme with this
