### ISSUE TITLE
rails 7.1 gemspec issue

### ISSUE THREAD

**Issue by courtsimas** [mbleigh/acts-as-taggable-on#1111]
This gem works great with rails 7.1.0rc2... I've been testing it for a week The gemspec of this gem should be updated to work with rails 7.1, otherwise the stable release of rails won't actually install with this gemspec conflict.

**Comment by aovertus** [comment]
https://github.com/mbleigh/acts-as-taggable-on/pull/1110

I've opened a PR for this, lets give it some voice to merge it 😁

**Comment by kapso** [comment]
Thanks @aovertus 

yea a merge would be nice.

**Comment by seuros** [comment]
Sorry for closing this issue: 

Can you test this PR ? https://github.com/mbleigh/acts-as-taggable-on/issues/1112

I will release it once i get few confirmations that it won't cause issue with different adapters.
