### ISSUE TITLE
Issue on Rails 7.1 upgrade

### ISSUE THREAD

**Issue by ajdubovoy** [mbleigh/acts-as-taggable-on#1112]
I just upgraded a project to Rails 7.1. It seems to actually run fine in the server, but I've started getting some red Rspec tests that seem to be related to this gem:

```
warning: already initialized constant ActsAsTaggableOn::Tagging::DEFAULT_CONTEXT
Failure/Error: let(:invitation) { create(:invitation, user:) }
     
     NoMethodError:
       undefined method `arity' for {:polymorphic=>true}:Hash
     
             if scope && scope.arity == 0
```

I get this same error on each test.

Thanks for your help!

**Comment by jon-sully** [comment]
I just ran into this as well. Everything actually works fine when running directly on `master`, and I think prior to, some dependency issues forced us to be running on a fairly old version (5.x.x?) to begin with. I think `master` is good for Rails 7.1.

**Comment by seuros** [comment]
Can you try https://github.com/mbleigh/acts-as-taggable-on/pull/1114 please.

**Comment by jon-sully** [comment]
Sure! Let me run it against our suite.

**Comment by jon-sully** [comment]
Yep, both master and v10 pre-release worked fine for me 👍

**Comment by seuros** [comment]
I will merge it and release it tomorrow then.

**Comment by jon-sully** [comment]
Sweet! 😎

**Comment by h0jeZvgoxFepBQ2C** [comment]
Great, waiting for the release.. Thank you so much!

**Comment by ajdubovoy** [comment]
Thank you so much for your help!!

**Comment by seuros** [comment]
Released
