### ISSUE TITLE
Issue on rails 7.2 update

### ISSUE THREAD

**Issue by armanivvv** [mbleigh/acts-as-taggable-on#1130]
Updated Rails and active record

`Because acts-as-taggable-on >= 10.0.0 depends on activerecord >= 6.1, < 7.2 and rails >= 7.2.0 depends on activerecord = 7.2.0, acts-as-taggable-on >= 10.0.0 is incompatible with rails >= 7.2.0. So, because Gemfile depends on rails ~> 7.2.0 and Gemfile depends on acts-as-taggable-on ~> 10.0, version solving has failed.`

Seems act-as-taggable-on activerecord dependency wants < 7.2 but with rails update it ends up with = 7.2

**Comment by rctneil** [comment]
+1 from me on this.

**Comment by Skulli** [comment]
See https://github.com/mbleigh/acts-as-taggable-on/pull/1126

**Comment by scoobyclub** [comment]
I created my own fork and updated the gemspec for 7.2 and it seems to work fine. Works as a stopgap anyway.

  gem.add_runtime_dependency 'activerecord', '>= 6.1', '< 7.3'

**Comment by rctneil** [comment]
Is this gem being updated to officially support 7.2?   Is it dead?

I'd rather keep using the official repo rather than one just quickly patched for support.

What is the official status of this gem from here on out?

**Comment by seuros** [comment]
Please try #1132  and let me know if there is any breaking in 7.2.

I removed dead code and fixed the build for 7.x 

I will release a new version if there is no new failure reported.

**Comment by jcoyne** [comment]
@seuros I've tried the PR and it works for us.

**Comment by seuros** [comment]
Releasing !

**Comment by armanivvv** [comment]
Amazing thanks, I just pulled it in and no issues to report.
