### ISSUE TITLE
Upgrading from sqlite3 1.7 to 2.2 gives error Encoding::UndefinedConversionError when saving a tag with special chars

### ISSUE THREAD

**Issue by wisedevman** [mbleigh/acts-as-taggable-on#1135]
Hi all,
after upgrading sqlite3 adapter gem from 1.7 to 2.2 I got an error saving tags with special chars like "à". 

```
a = Post.new            # Post is application record subclass
a.add_tag("Papà")
a.save
```
Error:
> .rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sqlite3-2.2.0-x86_64-linux-gnu/lib/sqlite3/statement.rb:31:in encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

I initially submitted a issue on sqlite3-ruby repo:
https://github.com/sparklemotion/sqlite3-ruby/issues/576

As it's related to this gem, I write here too.
Thank you

**Comment by seuros** [comment]
fixed in version 12.0.0
