### ISSUE TITLE
Changelog entry for 12.0

### ISSUE THREAD

**Issue by tagliala** [mbleigh/acts-as-taggable-on#1141]
Hello, is it possible to have a changelog entry for 12.0?

**Comment by elthariel** [comment]
There's only a limited number of commits since the last release. You can probably figure it out yourself, or, even better, contribute it !

**Comment by tagliala** [comment]
Sorry, I forgot that the myself of the past opened that issue

> You can probably figure it out yourself

In fact I did in ##1137, I will propose a PR

Having a changelog will help integration with Dependabot, which will source the changes to the opening post

Examples:

10 to 11: https://github.com/chileap/image-tagging-with-ai/pull/43
11 to 12: https://github.com/runteq/mob_pro_event_app/pull/10

**Comment by tagliala** [comment]
Reopening, this will be closed by #1143
