### ISSUE TITLE
#tagged_with_ids when tag ids are known

### ISSUE THREAD

**Issue by costa** [mbleigh/acts-as-taggable-on#163]
When using an autocompleting input control like http://loopj.com/jquery-tokeninput/ the tag ids are known, which makes it a performance waste to convert them back to tag names (not to mention joining tables inside tagged_with).

It's not a big issue with my current project (when the tags and taggables are few), but I'll definitely write and submit a patch along the lines of ModelName#tagged_with_ids when needed... unless someone would jump ahead before that.

**Comment by momolog** [comment]
We could also make good use of this. Having `ActsAsTaggableOn::Taggable::Core.tagged_with` accept arrays of **tag ids** in addition to arrays of **tag names** would make a lot of sense in situations where you have the tag ids already.
