### ISSUE TITLE
all_tag_counts sql not compatible with oracle (ORA-00905) missing keyword error

### ISSUE THREAD

**Issue by jhanzel** [mbleigh/acts-as-taggable-on#200]
Using rails 3.0.9 using acts-as-taggable-on 2.1.1

When you try to do a Document.all_tag_counts or document.all_tag_counts,  you get missing keywords: SELECT tags.*, taggings.count AS count FROM "TAGS" join (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM "TAGGINGS" INNER JOIN documents ON documents.id = taggings.taggable_id WHERE (taggings.taggable_type = 'Document' AND (taggings.taggable_id (SELECT documents.id FROM DOCUMENTS")) GROUP BY taggings.tag_id HAVING COUNT(taggings.tag_id) > 0) AS taggings ON taggings.tag_id = tags.id

While the sql is logically correct,  it is not valid syntax from oracle :(

If I back down to version 2.0.6 of the gem, this is no longer a problem.

**Comment by Kyrremann** [comment]
Not to wake up the dead, but this is stil an error in `3.5.0`.

**Comment by matt-steinwachs** [comment]
Still an error in 4.0.0

**Comment by hjansen** [comment]
Please reopen. The problem is still there in 4.0.0
