### ISSUE TITLE
error:  ActiveRecord::UnknownAttributeError (unknown attribute: context):

### ISSUE THREAD

**Issue by timfong888** [mbleigh/acts-as-taggable-on#23]
Hi,

Starting to use acts-as-taggable-on and easing in using as if on-steroids and get a "context" error.

class Vendor...
   acts_as_taggable_on :tags, :competitors

form_for @vendor |do|....

  <p>
    <%= f.label :tags %><br />
    <%= f.text_field :tag_list %>
  </p>

It looks like I have added it as the model with two types of context

And then in the view new created a field for submission.

But I'm still getting an error.  Thanks!

**Comment by jbhatab** [comment]
@eet-nu I'm getting this error in production on heroku but I have context on taggings. Any ideas?
