### ISSUE TITLE
ActiveRecord::StatementInvalid using "find_related_#{tag_type}"

### ISSUE THREAD

**Issue by andreydjason** [mbleigh/acts-as-taggable-on#239]
Hi, I was using "find_related_#{tag_type}" and encountered some bug (I think), when I use for example @article.find_related_tags ( even with - order: "count_all DESC" ) the return is a error:

``` ruby
Mysql2::Error: Unknown column 'count' in 'order clause': SELECT COUNT(*) AS count_all, articles.id AS articles_id FROM articles, tags, taggings  WHERE (articles.id != 4 AND articles.id = taggings.taggable_id AND taggings.taggable_type = 'Article' AND taggings.tag_id = tags.id AND tags.name IN ('sebrae','capacitação','gastronomia','alimentação fora de casa','Ceará','turismo','atendimento')) GROUP BY articles.id ORDER BY count DESC
```

So the solution for me (for now) is to change the file "lib/acts_as_taggable_on/acts_as_taggable_on/related.rb", lines 51:
- Instead of this:
  ```klass.scoped({ :select     => "#{klass.table_name}.*, COUNT(#{ActsAsTaggableOn::Tag.table_name}.#{ActsAsTaggableOn::Tag.primary_key}) AS count",

``````
- Use this:
```klass.scoped({ :select     => "#{klass.table_name}.*, COUNT(#{ActsAsTaggableOn::Tag.table_name}.#{ActsAsTaggableOn::Tag.primary_key}) AS count_all",
``````

And in line 65:
- Instead of this:
  ```klass.scoped({ :select     => "#{klass.table_name}.*, COUNT(#{ActsAsTaggableOn::Tag.table_name}.#{ActsAsTaggableOn::Tag.primary_key}) AS count",

``````
- Use this:
```klass.scoped({ :select     => "#{klass.table_name}.*, COUNT(#{ActsAsTaggableOn::Tag.table_name}.#{ActsAsTaggableOn::Tag.primary_key}) AS count_all",
``````

So now I can use find_related_tags(:order => 'count_all DESC') for example, and it works.

I also changed the :order options in this same file, in the same methods I described above, changed to :order => "count_all DESC" as a default option.

Its possible to do this without problems?

**Comment by devandy** [comment]
I still have this problem, version  (3.5.0)
