### ISSUE TITLE
*_list attribute not getting dirtied when updated has nested attribute

### ISSUE THREAD

**Issue by budu** [mbleigh/acts-as-taggable-on#257]
When you call `update_attrbutes` on a model which have nested attributes for a model where the only attribute that changes is a `*_list`, it doesn't work as the nested record doesn't get dirty.

**Comment by Skulli** [comment]
I am stil having issues with this on (version 4.0.0 and rails 4.2.7)

*empty start*

    g.document.marker_list = "test1, test2"
    g.save

that works, g.document.dirty? is also true
next

     g.document.marker_list = "test"
     g.save

that wont, also adding another one. It only works on the initial assignment when adding tags the first time. Document is not dirty.

to make it work i have to manually call

    g.document.save
