### ISSUE TITLE
Rails 4 protected attributes

### ISSUE THREAD

**Issue by MikeSilvis** [mbleigh/acts-as-taggable-on#389]
When upgrading to rails 4 and trying to modify tags via the `tag_list` method i get the following:

```
WARNING: Can't mass-assign protected attributes for ActsAsTaggableOn::Tagging: tag_id, context, taggable
```

**Comment by gmcnaughton** [comment]
Starting with acts-as-taggable-on 4.0.0, `Tagging` needs `:tag` on the list of attributes to make accessible as well.
