### ISSUE TITLE
Version 3.0.0 incurs MySQL 'LIMIT & IN/ALL/ANY/SOME subquery'" error

### ISSUE THREAD

**Issue by dannguyen** [mbleigh/acts-as-taggable-on#450]
Observed on 
- Ruby 1.9.3
- Rails 3.2.16
- MySQL 5.6.15 for osx10.9 (x86_64)

Just noticed that the latest version (which was uploaded within the hour) seems to fall afoul of a known-MySQL limitation

>  Mysql2::Error: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery':

Checkout this issue for delayed_job_active_record:
https://github.com/collectiveidea/delayed_job_active_record/issues/32

Apparently it also breaks for Postgres 8.4:
https://github.com/collectiveidea/delayed_job_active_record/issues/32#issuecomment-13714740

Things work as normal for me when I switch back to 2.4.1

The full error for completeness sake:

> Mysql2::Error: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery': SELECT SUM(tags_count) AS sum_id FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` INNER JOIN myrecords ON myrecords.id = taggings.taggable_id WHERE (taggings.taggable_type = 'MyRecord AND taggings.context = 'hashtags') AND (taggings.taggable_id IN(SELECT  myrecords.id FROM `myrecords`  WHERE `myrecords`.`user_id` = 111 ORDER BY created_at DESC LIMIT 1000)) GROUP BY taggings.tag_id HAVING COUNT(taggings.tag_id) > 0) AS taggings ON taggings.tag_id = tags.id

**Comment by gmcnaughton** [comment]
Since pull #457 was merged, is this issue now fixed?

**Comment by dannguyen** [comment]
Thanks for pinging me!
