### ISSUE TITLE
Tagger and Taggable can have a non-integer ID

### ISSUE THREAD

**Issue by seuros** [mbleigh/acts-as-taggable-on#477]
When we use

```
   t.references :taggable, :polymorphic => true
   t.references :tagger, :polymorphic => true
```

Rails generates : 

```
    t.integer   "taggable_id"
    t.string   "taggable_type"
    t.integer   "tagger_id"
    t.string   "tagger_type"
```

I think we should find a way to migrate existing data  to : 

```
    t.string   "taggable_id"
    t.string   "taggable_type"
    t.string   "tagger_id"
    t.string   "tagger_type"
```

to accept models with uuid/string/integer in theirs primary key.

/cc @mbleigh @bf4

**Comment by jaymiejones86** [comment]
+1 for the version 4.

**Comment by jeansimon** [comment]
Would love to see this in version 4.

**Comment by lichtamberg** [comment]
How is the status of this?

**Comment by lichtamberg** [comment]
Can someone tell me how to make this work with rails 3.2?

**Comment by sur** [comment]
Instead of splitting the references,
please see this: https://github.com/mbleigh/acts-as-taggable-on/issues/698
