### ISSUE TITLE
How do I enable tags that have commas? 

### ISSUE THREAD

**Issue by vanboom** [mbleigh/acts-as-taggable-on#478]
Comment.tagged_with("Fish, Meat, or Chicken") is the same as Comment.tagged_with(["Fish","Meat","Chicken")

How do we enable an exact match, i.e. I want the tag to be "Fish, Meat, or Chicken"? 

thanks,
Don

**Comment by AmitJoki** [comment]
Well, you can always change the delimiter to something other than `,` but then you've to make sure that the delimiter isn't used in the tag names.

**Comment by seuros** [comment]
Or code your own parser.
