### ISSUE TITLE
tagger_id and tagger_type not working while using with devise current_user

### ISSUE THREAD

**Issue by mistergiri** [mbleigh/acts-as-taggable-on#485]
Can you give me a fix for this.?

 tagger_id and tagger_type has null values while using with devise current_user

**Comment by AlexVPopov** [comment]
I think this issue can be closed, @flamontagne has explained and solved the problem pretty well. I've tried to sum it up [here](http://stackoverflow.com/questions/3619361/update-owner-tags-via-form/31687528#31687528).
