### ISSUE TITLE
PG TR Deadlock Detected after addition of taggings_count

### ISSUE THREAD

**Issue by forest** [mbleigh/acts-as-taggable-on#507]
Just upgraded to v3.1.1 and I'm seeing a deadlock. I have 25 sidekiq (threaded) workers running and importing data. Each process is creating many tags.

```
WARN: PG::TRDeadlockDetected: ERROR:  deadlock detected
DETAIL:  Process 2546 waits for ShareLock on transaction 258000; blocked by process 2547.
Process 2547 waits for ExclusiveLock on tuple (74,46) of relation 45545 of database 19986; blocked by process 2554.
Process 2554 waits for ShareLock on transaction 257999; blocked by process 2546.
HINT:  See server log for query details. 
: UPDATE "tags" SET "taggings_count" = COALESCE("taggings_count", 0) - 1 WHERE "tags"."id" = 5849
```

**Comment by whistlerbrk** [comment]
@seuros is there a way to update tag counts after a batch run assuming I've disabled it as shown above? I'd like to still use the feature but just disable it during batch runs

**Comment by whistlerbrk** [comment]
The counter cache is a standard standard Rails counter cache.

As a quick fix, after a run you can do this: 

```
ActsAsTaggableOn::Tag.pluck(:id).each do |id|
   ActsAsTaggableOn::Tag.reset_counters(id, :taggings)
end
```

But (@forest) perhaps a better solution is using something like this if you actually want the feature:
https://github.com/wanelo/counter-cache

**Comment by dpflucas** [comment]
@whistlerbrk I tried to execute

```
ActsAsTaggableOn::Tag.pluck(:id).each do |id|
   ActsAsTaggableOn::Tag.reset_counters(id, :taggings)
end
```

inside my sidekiq worker, but I get the following error:

```
NoMethodError: undefined method `counter_cache_column' for nil:NilClass
```

However, the same code executes without problems in the rails console. Any suggestion?

**Comment by gingerlime** [comment]
Also bumped into this issue and trying to figure out the best workaround. Is it possible to disable counters for a subset of our tags / models? but keep them for others?

**Comment by gingerlime** [comment]
... somehow I'm still getting deadlock errors even after setting `ActsAsTaggableOn.tags_counter = false` inside my sidekiq job

```
PG::TRDeadlockDetected: ERROR:  deadlock detected\nDETAIL:  Process 24245 waits for ShareLock on transaction 55696; blocked by process 24246.\nProcess 24246 waits for ShareLock on transaction 55694; blocked by process 24245.\nHINT:  See server log for query details.\nCONTEXT:  while updating tuple (43,158) in relation \"tags\"\n: UPDATE \"tags\" SET \"taggings_count\" = COALESCE(\"taggings_count\", 0) + 1 WHERE \"tags\".\"id\" = 92
```

my job looks something like this:

```ruby
class Worker
  include Sidekiq::Worker
  def perform(ids)
    ActsAsTaggableOn.tags_counter = false
    ActiveRecord::Base.transaction do
      MyModel.where(:id => ids).delete_all
      # ... recreating models with tags
    end
  end
end
```

Am I doing it wrong?

**Comment by titame** [comment]
@gingerlime , I am also facing same issue even after disabling tags_counter. Sidekiq job failing due to deadlock error. Did you get any solution on this?

Thanks.

**Comment by gingerlime** [comment]
@titame I didn't really solve it. I just made sure things don't run concurrently, but rather sequentially... Not the prettiest workaround, but it was the best we could do.

**Comment by ErvalhouS** [comment]
I've had the same problem when using a task with both .destroy_all and .update in batch. Solved it by using .delete_all instead.

**Comment by vlasiak** [comment]
I experienced the same issue today as well, even after disabling `tags_counter`.
In my case the root of the problem was in concurrent manipulations with tags in a `sidekiq` jobs.
So, as a fast solution, I came up with using [with_advisory_lock gem](https://github.com/ClosureTree/with_advisory_lock) and wrapped the code, causing deadlocks, in it. Seems to be working stable now.

**Comment by jdarnok** [comment]
This fixed issue for us. The cons of that are that we limit the number of threads but we don't experience the deadlock again. 
https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#concurrent
