### ISSUE TITLE
update_attributes without :tag_list key sets tag_list to []

### ISSUE THREAD

**Issue by snitko** [mbleigh/acts-as-taggable-on#547]
I have a problem while updating the model that is taggable. If I call update_attributes, but without the `:tag_list` - then all tags are removed from this object. Example:

```
q = Question.create(title: "How do I create tags?", tag_list: "ruby, rails, programming")
q.tag_list #=> ["ruby", "rails", "programming"]
q.update_attributes(title: "How do I delete tags?")
q.tag_list #=> []
```

So wrong. If I don't touch `:tag_list`, it shouldn't delete all of the existing tags on this model.

**Comment by aldosolis** [comment]
Any solution to this yet? I got the same problem in the following context:

User has one Login

user = User.find(1)
user.update_attributes(login_attributes: { id: user.login.id, udf_list: "a, b, c", first_name: "Aldo" })

problem: model.login.name is updated but model.logins.tag_list is not updated
