### ISSUE TITLE
Destroying Tag Parent would also destroy tags

### ISSUE THREAD

**Issue by davidchua** [mbleigh/acts-as-taggable-on#550]
I have a Tag Parent Model called "Deal" which has tags and is also running the acts_as_paranoid gem. When I call a @deal.destroy, the tags that is linked to Deal is destroyed even though technically the Deal has not been destroyed from the database.

How can I prevent acts_as_taggable_on from acting on destroy dependency?

**Comment by tridnguyen** [comment]
Does this still work with the latest version?  I tried adding it to my model, but the taggings record still get destroyed when the taggable is destroyed.
