### ISSUE TITLE
Rails 4.2 Can't modify frozen hash ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by the-teacher** [mbleigh/acts-as-taggable-on#580]
I have `Can't modify frozen hash ActiveSupport::HashWithIndifferentAccess` when I do `blog.tag_list = "hello"` with rails 4.2

Now I dont know how to fix it.

**Comment by jnankin** [comment]
Will a new version of the gem come out that contains this fix?  Right now it looks like I'll have to tie this to a master commit in my Gemfile to get this fix.
