### ISSUE TITLE
Documentation doesn't include any information on how to manage a global tag list by context

### ISSUE THREAD

**Issue by taimoorq** [mbleigh/acts-as-taggable-on#606]
The current documentation focuses only on tags that are attached (or being attached) to objects. What I cant find much mention of is how to add/edit/delete tags (within a particular context) from a global list of tags regardless of whether they are attached to any model at that particular time. This is useful in instances where you dont want your users to create their own tags and need them to pick from a set list.

Any examples on how this can be done would be appreciated. For example, how can I put together a simple CRUD for a master list of tags within a particular context?

**Comment by lenart** [comment]
Before I reinvent the wheel - did any of you guys (@taimoorq, @nathanpsouza, @DaniG2k) manage to find an example of this somewhere?

**Comment by DaniG2k** [comment]
Not I

**Comment by taimoorq** [comment]
Don't have time to write up the full solution i went with right now, but basically I added the <a href="https://github.com/collectiveidea/awesome_nested_set">awesome nested set</a> gem to my application and then managed the tags table with it. I had to update the forms that allow tagging to only allow selection form a predefined list and that list was a nested tree from the tag table.

**Comment by richlarcombe** [comment]
This would be really useful.
