### ISSUE TITLE
:match_all => true does not work as intended

### ISSUE THREAD

**Issue by murtali** [mbleigh/acts-as-taggable-on#611]
I have a model 

```
class Activity
  acts_as_taggable_on :seasons
end
```
After creating a record with tags "Spring" and "Summer"

when doing:
```
Activity.tagged_with(["Summer"], :on => :seasons, :match_all => true)
```
=> returns nothing (#<ActiveRecord::Relation []>)

when doing:
```
Activity.tagged_with(["Summer", "Spring"], :on => :seasons, :match_all => true)
```
=> returns the proper activity object

My use case is if I have an array of activities that have been tagged with "summer", I want a count of those activities that also have the tag "spring"

thanks

**Comment by seuros** [comment]
I'm sorry for the late delay, i was busy with other projects. 

match_all => true mean that all the tags a record should have all the tags before it fetched.

You are want to use `:any => true`

**Comment by murtali** [comment]
So the :match_all => true is an exact match?

```
Activity.tagged_with(["Summer"], :on => :seasons, :match_all => true) #=> returns a record that has ONLY "Summer" ? which in this case is none
```
vs 
```
Activity.tagged_with(["Summer", "Spring"], :on => :seasons, :match_all => true) #=> returns record with Summer AND Spring BOTH
````

am I understanding that correct?

**Comment by seuros** [comment]
I think this will work : Activity.tagged_with(["Summer", "Spring"], :on => :seasons)
