### ISSUE TITLE
NoMethodError: undefined method `reload' for nil:NilClass

### ISSUE THREAD

**Issue by fascox** [mbleigh/acts-as-taggable-on#612]
trying to remove an object with tags throws this exception:

irb(main):017:0> a = Article.find 7002
irb(main):018:0> a.destroy

NoMethodError: undefined method `reload' for nil:NilClass
	from /home/nikeita/fastroad/shared/bundle/ruby/2.1.0/gems/acts-as-taggable-on-3.4.2/lib/acts_as_taggable_on/tagging.rb:36:in `remove_unused_tags'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:424:in `block in make_lambda'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:221:in `call'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:292:in `destroy'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:263:in `block in destroy'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:263:in `destroy'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/persistence.rb:167:in `destroy!'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/has_many_association.rb:112:in `each'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/has_many_association.rb:112:in `delete_records'
... 25 levels...
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:263:in `destroy'
	from (irb):18
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:43:in `require'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:43:in `block in exec_app_rails'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:32:in `loop'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/app_rails_loader.rb:32:in `exec_app_rails'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/cli.rb:5:in `<top (required)>'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/bin/rails:9:in `require'
	from /home/nikeita/fastroad/releases/132/vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/bin/rails:9:in `<top (required)>'
	from bin/rails:16:in `load'
	from bin/rails:16:in `<main>'irb(main):019:0>

**Comment by pvbraga** [comment]
I'm having this problem. Where do I put this piece of code?

`ActsAsTaggableOn::Tag.find_each do |tag|
  ActsAsTaggableOn::Tag.reset_counters(tag.id, :taggings)
end`

**Comment by chuckbjones** [comment]
It should only be needed if you are modifying the database outside of the application.

I run it as part of a rake task that imports data from a db backup:
https://github.com/txstate-etc/signup/blob/3a1bbcc/lib/tasks/db.rake#L60
