### ISSUE TITLE
rails 4.2 text_field issue

### ISSUE THREAD

**Issue by ghost** [mbleigh/acts-as-taggable-on#620]
Hi. I'm using ruby 2.1.5 and recently upgraded to rails 4.2. I noticed ActionView::Helpers::Tags::TextField no longer calls html_safe on its value, which means that for a post with tag_list ['ruby', 'rails'], the following erb block
`<%= f.text_field :tag_list %>`
produces
`<input type="text" value="ruby rails" name="post[tag_list]" id="post_tag_list">`
rather than
`<input type="text" value="ruby, rails" name="post[tag_list]" id="post_tag_list">`

It's easily fixed by
`<%= f.text_field :tag_list, value: @post.tag_list.to_s %>`
but I was wondering if there's a way to go about this issue without having to specify the value option each time?

**Comment by lenart** [comment]
Not being able to use Rails' form helpers "out of the box" feels a bit weird to me as well.

Could @seuros or @bf4 explain why you decided to take this approach? You mentioned security but I'd like to understand this better.

**Comment by stiff** [comment]
Maybe just add `glued_tag_list` and `glued_tag_list=` to use in forms?

**Comment by openscript** [comment]
What kind of security feature are you talking about?

**Comment by ThreeWest** [comment]
Neither of the suggestions work for me. :( With no workaround, acts_as_taggable_on essentially no longer works for my app since, with no commas, a record would have to have the exact same string of tags to match any other record which is highly improbable. Maybe the suggestions didn't work because I'm using simple_form.

**Comment by tirdadc** [comment]
Why was this closed when no explanation for this change was provided?

**Comment by ScotterC** [comment]
This should be noted in a changelog somewhere because on upgrade to 4.2 I had some production projects lose tag data because when the resources were saved again the commas were lost and it created new tags.

**Comment by AlexVPopov** [comment]
Created a [wiki-page](https://github.com/mbleigh/acts-as-taggable-on/wiki/Add-a-tag-field-to-forms-in-Rails--4.2-and-above), addressing this issue.

**Comment by carlflor** [comment]
For `simple_form` it's like this:

`<%= f.input :tag_list, input_html: {value: @something.tag_list.to_s} %>`

**Comment by korny** [comment]
This was our solution:

```ruby
module ActionView::Helpers::TagHelper
  private
  def tag_option_with_tag_list_support(key, value, escape)
    if value.is_a?(ActsAsTaggableOn::TagList)
      value = escape ? safe_join(value, ActsAsTaggableOn.glue) : value.join(ActsAsTaggableOn.glue)
    end

    tag_option_without_tag_list_support key, value, escape
  end
  alias_method_chain :tag_option, :tag_list_support
end
```
