### ISSUE TITLE
@acts_as_taggable_on_cache_columns should be reset by reset_column_information

### ISSUE THREAD

**Issue by warp** [mbleigh/acts-as-taggable-on#621]
If its not reset then columns will continue to return the cached value and not requery the database as expected.

**Comment by warp** [comment]
I see the cache has been removed in master

**Comment by seuros** [comment]
I don't think so, that will be a breaking change and a regression.

**Comment by warp** [comment]
Yeah my mistake it was github search playing tricks on me :)
