### ISSUE TITLE
Support Mongoid

### ISSUE THREAD

**Issue by yordis** [mbleigh/acts-as-taggable-on#664]
Hey guys, I really love this gem, actually, is one my favorites and useful but world is changing and the demand of MongoDB in growing up. 

Is there any consideration of support Mongoid?

**Comment by seuros** [comment]
Are you willing to add it and maintain that support ?

**Comment by yordis** [comment]
Is that difficult at this point of the project?

**Comment by seuros** [comment]
While some parts might be used, most of the codebase will need updating. 
I think it just better to have a similar gem for mongoid  instead .

**Comment by yordis** [comment]
ya, I am getting that concern about everything for Mongoid is just a copy of existing gem :( So basically we are going to have the same problem fixed two different ways.

I don't say always have to be one but I like create some core layer and then adapt to different environments but I understand.

This is a good implementation: https://github.com/wilkerlucio/mongoid_taggable I would like to see this get merge into one in the future
