### ISSUE TITLE
Tags with commas don't seem to work properly

### ISSUE THREAD

**Issue by kris** [mbleigh/acts-as-taggable-on#667]
Hi,

I'm in a situation where some tags (unfortunately) have commas. Here is an example:

    @doctor.category_list = "ear, nose, and throat"

This returns three tags:

    ["ear", "nose", "and throat"]

A solution is to use quotes:

    @doctor.category_list = "'ear, nose, and throat'"

And it seems to look good by giving me the tag `"ear, nose, and throat"`:

    => #<ActiveRecord::Associations::CollectionProxy [#<ActsAsTaggableOn::Tag id: 7221, name: "ear, nose, and throat", taggings_count: 1>]>

If you look closely, the "ear, nose, and throat" is stripped of quotes, which means when the object is reloaded, it reparses and the results come back as `["ear", "nose", "and throat"]`

Am I missing something in the process here?

Thanks!

**Comment by seuros** [comment]
You can build your own parser and inherite it from the GenericParser.

**Comment by kinnrot** [comment]
I use

`# To support tags with commas
module ActsAsTaggableOn
  class TagParser < GenericParser
    TAG_LIST_SEPARATOR = '|'

    def parse
      TagList.new.tap do |tag_list|
        tag_list.add @tag_list.split(TAG_LIST_SEPARATOR).flatten.map(&:strip).reject(&:empty?)
      end
    end
  end
end`

And added initializer

`require 'acts_as_taggable_on/tag_parser'

ActsAsTaggableOn.default_parser = ActsAsTaggableOn::TagParser
`

the parser is inside lib/acts_as_taggable_on
