### ISSUE TITLE
Is using tagged_with(params[:tag]) safe?

### ISSUE THREAD

**Issue by robyedlin** [mbleigh/acts-as-taggable-on#670]
Is this a safe implementation?

tagged_with(params[:tag])

Do the params need to be sanitized in Rails 4 with tagged_with?

**Comment by seuros** [comment]
I will pass them through the parser first.

**Comment by robyedlin** [comment]
Like tagged_with(#{params[:tag]})?

**Comment by seuros** [comment]
This parser for example: https://github.com/mbleigh/acts-as-taggable-on/blob/master/lib/acts_as_taggable_on/default_parser.rb , you can use your own.

**Comment by robyedlin** [comment]
Ok, thanks.
