### ISSUE TITLE
What happens if a same tag is added again?

### ISSUE THREAD

**Issue by AmitJoki** [mbleigh/acts-as-taggable-on#677]
I have tags for a post. Say foo. A user can "follow" foo.

So, I'd add "foo" tag to both post and user models. My concern is that will "foo" be created twice or will  it be generated just once and it's reference is held by the two models?

**Comment by seuros** [comment]
```foo``` will be in the ```tags``` table, and ```taggings``` will have 2 record (referencing user and post)

**Comment by AmitJoki** [comment]
ah great. That means the tag isn't being duplicated. Only reference aka their id is. That's how it's supposed to work, but had my doubt. Thanks mate :+1:
