### ISSUE TITLE
Any support for numerical tags?

### ISSUE THREAD

**Issue by AmitJoki** [mbleigh/acts-as-taggable-on#678]
Suppose the case is such that each user can follow n users, I'd want to add their ids as tags. As of now, I'd have to convert them to strings and retrieve by string.

Is there a better way of doing this?

**Comment by seuros** [comment]
don't use this gem, that will be a hack. Checkout acts as follower or similar gems.

**Comment by AmitJoki** [comment]
Ah okay. That's cool. Thanks man. You're a great help.
