### ISSUE TITLE
Finding all objects with tag

### ISSUE THREAD

**Issue by Svashta** [mbleigh/acts-as-taggable-on#685]
Hi,

not really an issue but more as a general question.
I have a tag cloud of all the tags in the system (ActsAsTaggableOn::Tag.all).
Now, I would like each of the tags to be a link to a list of all the objects that are tagged with this tag.
I don't find a way to find all related objects (model records).

I understand how to do it on a particular, known, model.
But what about any model?

**Comment by seuros** [comment]
probably you have to use ActsAsTaggableOn::Tagging and group them.
