### ISSUE TITLE
Access tag_list from AngularJS ng-repeat

### ISSUE THREAD

**Issue by chrisvel** [mbleigh/acts-as-taggable-on#704]
I am trying to access the tag_list from an AngularJS RESTful API. The model that acts as taggable is called Note (something like a Post actually) and works fine (tested) as `mynote.tag_list` in Rails. In AngularJS it seems that it shows nothing.

```
<div class="ui divided padded items" ng-controller="SidebarController">
  <a href="#/notes/{{note.id}}" ng-class="{active: isItemActive(note)}"
   class="item note-a ui" ng-repeat="note in notes | orderBy: '-created_at'">
    <h4 class="ui header note-header">
      {{ note.title }}
    </h4>
    <a ng-click="destroy($index)"
       href=""><i class="ui icon remove"></i></a>
    <div class="extra">
      <div ng-repeat="tag in note.tag_list">
        {{ tag }}
      </div>
    </div>
  </a>
</div>
```

and

```
var app = angular.module('notepadApp');

app.controller('SidebarController',
  ['$scope', '$http', '$routeParams', '$location', 'Note', 'ShareNoteScope',
    function($scope, $http, $routeParams, $location, Note, ShareNoteScope) {

    $scope.notes = Note.query();
  }]
);
```

It's pretty simple but I don't know how is it possible.

**Comment by yjukaku** [comment]
@chrisvel This is not really related to acts-as-taggable-on, it's more of a coding question that you can get help with on StackOverflow

Regardless, the problem may be that note.tag_list is coming from your API as a string, not an array, so `nr-epeat="tag in note.tag_list"` might be silently failing.

@mbleigh IMO This issue can be closed.
