### ISSUE TITLE
How to tag a model automatically?

### ISSUE THREAD

**Issue by ivanoblomov** [mbleigh/acts-as-taggable-on#707]
I've tried adding a standard `tag_list.add :tag_label` as a `before_save` callback but, perhaps predictably, this results in an infinite loop as `save` must be called after the `add` for the tagging to persist.

What's the best practice to tag a model automatically based on arbitrary conditions?

**Comment by rishijain** [comment]
I did this and it works fine.

In `app/model/post.rb`
```ruby
class Post < ActiveRecord::Base
  acts_as_taggable_on :skills
  before_save :add_skill

  def add_skill
    self.skill_list.add("skill-#{Time.now.to_i}")
  end

end
```

Upon doing 
```ruby
p  = Post.new
p.save
```

It adds new skills and the data persists.

**Comment by ivanoblomov** [comment]
Inexplicably, the recursion only happens in app or from within a Cucumber feature.

**Comment by ivanoblomov** [comment]
My bad, this was a problem specific to my implementation!
