### ISSUE TITLE
Current alpha breaks Rails 5 ActiveRecord::Sanitization#quoted_id

### ISSUE THREAD

**Issue by ffmike** [mbleigh/acts-as-taggable-on#712]
The changes to core.rb at https://github.com/mbleigh/acts-as-taggable-on/commit/d7ac3b0c17f992bed903f20a7ce9e143c0397e0e break the quoted_id method in Rails (which, though slated for deprecation, is still used) by putting in a private quote_value method.

Originally reported at https://github.com/rails/rails/issues/22847 but it's not Rails' problem.

Removing the private from acts_as_taggable_on fixes, but there may be a better fix.

**Comment by brauliobo** [comment]
got hit by this too :(

**Comment by gmcnaughton** [comment]
I got the same error on Rails 4.2.7, after upgrading from 3.5.0 -> 4.0.0.

It happens if I pass a model to a dynamic finder method:
```
u = User.first
User.find_by_id(u.id) # <= #<User ...>
User.find_by_id(u)
NoMethodError: private method `quote_value' called for #<Class:0x007fd0f39a2998>
  from lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  from lib/active_record/sanitization.rb:188:in `quoted_id'
  from lib/active_record/connection_adapters/abstract/quoting.rb:10:in `quote'
  from lib/active_record/statement_cache.rb:51:in `block in sql_for'
  from lib/active_record/statement_cache.rb:51:in `each'
  from lib/active_record/statement_cache.rb:51:in `sql_for'
  from lib/active_record/statement_cache.rb:105:in `execute'
  from lib/active_record/core.rb:187:in `find_by'
  from lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
```
Passing a model instead of an id to 'find_by_id' is probably a mistake, but it is something that Rails allows!

**Comment by rogerneel** [comment]
I also got hit by this in a Rails 4.2 upgrade and can confirm that @gmcnaughton's fix is 👍 ...thanks!

Is this merge on the team's radar?
