### ISSUE TITLE
Extending tag model for custom scopes

### ISSUE THREAD

**Issue by amnesia7** [mbleigh/acts-as-taggable-on#716]
Is there a way to extend the tag model that this gem provides? If so, a quick code example would be good.

I want to add a postgres search scope so that I can use `tsearch`/`pg_search` to do an autocomplete for tags.

Thanks

**Comment by amnesia7** [comment]
@the-teacher I noticed https://github.com/mbleigh/acts-as-taggable-on/issues/508 which seemed to imply that you had managed to extend the tag model using a concern so that you could add your own slug and validation.

Can you advise what code needs to go in what files to do that. I assume that's what I need to do to be able to add my own custom scopes or is there an even simpler approach somehow.

Thanks

**Comment by the-teacher** [comment]
@amnesia7 

hello! Sorry, but this task is out of my scope at this moment. Answer was not found. I solved this task with my own tags implementation (if I can remember it correctly). I can't do any advice how to improve this code.

Good luck!

**Comment by amnesia7** [comment]
Closing this because I decided the easiest way was to just put some custom `.where` and `.order` in my tags controller instead. I still think it might be good if the tags model was extendable though.

**Comment by dam13n** [comment]
@amnesia7 

You can do this (just did myself). This is the example I followed: http://blog.paulrugelhiatt.com/ruby/rails/2014/10/27/rails-admin-custom-action-example.html
