### ISSUE TITLE
tag_list sends extra ""

### ISSUE THREAD

**Issue by chrishough** [mbleigh/acts-as-taggable-on#730]
I just started noticing that this gem is sending an extra empty string with my check boxes as shown:

```
"language_list"=>["english", "spanish", ""],
```

This seems rather odd.  Here is the simple form code for the form:

```
= j.input :language_list, as: :check_boxes, collection: @tags
```

**Comment by san** [comment]
This is a Rails thing. Rails adds an extra hidden input with blank value. From your code snippet, I am guessing you are using SimpleForm. If you are, see this: https://github.com/plataformatec/simple_form/issues/603

**Comment by chrishough** [comment]
Thank you for the feedback, that appears to have worked for now.
