### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by nikhilm492** [mbleigh/acts-as-taggable-on#765]
I get the following issue on bundle update to rails 5

acts-as-taggable-on was resolved to 3.1.0, which depends on
      actionpack (< 5, >= 3)

**Comment by seuros** [comment]
try with master for now. 
We are still fixing some issues with some edge cases in activerecord 5 . I plan to release a version this weekend.

**Comment by krzysiek1507** [comment]
@seuros do you have any idea how to deal with Rails 5.0.0 error for this spec?
`#<SystemStackError: stack level too deep>`
https://github.com/mbleigh/acts-as-taggable-on/blob/master/spec/acts_as_taggable_on/taggable_spec.rb#L400
