### ISSUE TITLE
Migration installation conflict with spree gem

### ISSUE THREAD

**Issue by arpitchauhan** [mbleigh/acts-as-taggable-on#773]
acts-as-taggable-on version: 4.0.0

I'm trying to upgrade spree from 3.0 to 3.1 but there is a conflict while executing

`bundle exec rake railties:install:migrations`

because both spree gem and acts-as-taggable-on try to add migrations with the same name `AddMissingIndexes`

Manual renaming of one of the two migrations is not that helpful because if one runs `railties:install:migrations` is not considered already copied and thus is copied again.

I suggest renaming your migration to something else, eg `AddMissingIndexes`

I may try to create a PR.

**Comment by seuros** [comment]
go ahead please.

**Comment by arpitchauhan** [comment]
I did create a [PR](https://github.com/mbleigh/acts-as-taggable-on/pull/774)

**Comment by seuros** [comment]
Awesome , thanks
