### ISSUE TITLE
Bug: Database migration script - Tries to create tables tags and taggings even if they already exist

### ISSUE THREAD

**Issue by danowar2k** [mbleigh/acts-as-taggable-on#778]
Hello,

I'm currently trying to upgrade my Redmine from 2.5.1 to 3.3.0.

In the process I updated the redmine_tags plugin which uses your actsastaggable gem. The gem migration didn't work because the migration script doesn't even check if tags and taggings already exists, and therefore breaks.

Could you fix this?

**Comment by danowar2k** [comment]
Also in the second migration script...
An index is created even if it already exists...
(This seems to be not a migration, but an initial installation code)

**Comment by danowar2k** [comment]
Indices are removed if they don't exist...

**Comment by davingee** [comment]
same issue

**Comment by danowar2k** [comment]
Is this fixed? Or is a pull request still wanted?

**Comment by danowar2k** [comment]
Seems to be fixed...
