### ISSUE TITLE
Feature Request: Tag's Closest Neighbors

### ISSUE THREAD

**Issue by bouchard** [mbleigh/acts-as-taggable-on#78]
Thanks for the great work on this gem, it works wonderfully.

One feature I'm missing that'd I'd like to be considered for implementation is, for lack of a better term, a tag's "closest neighbors".

Given a tag A, what tags B, C, etc. are most commonly associated with a given object along with A?

This would allow for much more intuitive autocomplete on the client side, say if I often tag a user as "unprivileged, beginner, newbie", then:

User.first.nearest_tags("beginner")
=> [#<ActsAsTaggableOn::Tag id: 2, name: "unprivileged", associations: 6>, #<ActsAsTaggableOn::Tag id: 1, name: "newbie", associations: 4>]

Thoughts?

**Comment by trostli** [comment]
Best way to accomplish this IMO is to index the tags in soemthign like Elastic Search and do a similarity query. Check out the great gem Searchkick for this.
