### ISSUE TITLE
Removing acts-as-taggable-on gem

### ISSUE THREAD

**Issue by nkabbara** [mbleigh/acts-as-taggable-on#815]
Hello,

How do I create a migration to destroy all tables associated with this gem? I can't seemt find any instructions.

**Comment by bf4** [comment]
@nkabbara Since you created them, you're probably in the best place to remove them. Perhaps find the migration that added them? If you're asking how to create a migration that drops tables, that'll be in the Rails docs.

**Comment by nkabbara** [comment]
No doubt, but I was expecting something like rake acts_as_taggable_on_engine:uninstall to clean things up for me.
