### ISSUE TITLE
Rails 5.0.2 commas separating tags are being removed when tags are displayed in a text field

### ISSUE THREAD

**Issue by spaquet** [mbleigh/acts-as-taggable-on#816]
View (same code used to create and update):
```
<div class="form-group">
    <%= f.label :tag_list, "Tags (comma separated)" %>
    <%= f.text_field :tag_list, class: "form-control", placeholder: "Add tags" %>
 </div>
```
Model and corresponding controller are modified as explained in the documentation

When creating a new article with tags, they are properly stored in DB and displayed if rendered using 
`<%= @article.tag_list %>`: tag1, tag2, tag3

However, when editing the same article tags are set as 1 tag and the commas separating each of them is removed.

Rails: version 5.0.2
PostgreSQL
act-as-taggable-on from git

**Comment by spaquet** [comment]
Answer is in the Wiki...

**Comment by amitsaxena** [comment]
The solution can be found here:
https://github.com/mbleigh/acts-as-taggable-on/wiki/Add-a-tag-field-to-forms-in-Rails--4.2-and-above
