### ISSUE TITLE
Tags with underscores get escaped

### ISSUE THREAD

**Issue by chevinbrown** [mbleigh/acts-as-taggable-on#864]
Being a ruby shop, we'd like to have tags that use underscores instead of dashes. ie `big_pandas` instead of `big-pandas`.

Looking at the utils, for postgres, the escape character is `!`, but shouldn't it be `\\`?

Will be happy to submit a PR to fix this if you agree.

**Comment by rsl** [comment]
would love to see this as well

**Comment by lunaru** [comment]
@chevinbrown are you guys still planning to put up a PR for this?

**Comment by chevinbrown** [comment]
@rsl @lunaru we haven't started one, but looks like it would be appreciated by the community. @dwilkins this would be a good team effort.

**Comment by rsl** [comment]
Welcome comments on my PR, everyone. Thanks.
