### ISSUE TITLE
rake acts_as_taggable_on_engine:install:migrations doesn't work with rails 5.1

### ISSUE THREAD

**Issue by spnkr** [mbleigh/acts-as-taggable-on#866]
1. need to inherit from ` ActiveRecord::Migration[5.1]`, not ` ActiveRecord::Migration`
2. the indexes it adds in these auto generated migrations have duplicates, and so `rake db:migrate` fails

**Comment by kuwze** [comment]
I got rid of this by having this in my Gemfile:

> gem 'acts-as-taggable-on', '~> 5.0'

and deleting `vendor/bundle` and rerunning `bundle`

**Comment by lightbe** [comment]
I was having the same problem because it installed version 4. I reinstalled version 5 and got my databases created successfully.
