### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by jfish3** [mbleigh/acts-as-taggable-on#870]
Are there any maintainers left? The issues seem to be stacking up and no commit activity in 6 months...

**Comment by glendel** [comment]
Please go to here : [Pull Request #887](https://github.com/mbleigh/acts-as-taggable-on/pull/887) to see all the ready to merge and to use solutions to work with Rails 5.2! It is fully tested and ready to go! It is just missing to merge the changes into the main project!

This gem should be handled and administrated by the Ruby and Rails community!

**Comment by seuros** [comment]
Let release a new version this week.
