### ISSUE TITLE
Rails 5.2 compatibility?

### ISSUE THREAD

**Issue by rgbskills** [mbleigh/acts-as-taggable-on#874]
Hey guys I am trying to make this work in rails 5.2 but I am having trouble.

<img width="788" alt="screen shot 2017-12-15 at 15 35 11" src="https://user-images.githubusercontent.com/5773622/34044428-94f1a07e-e1ad-11e7-8dcd-9f44e1f6cb61.png">

**Comment by jkburges** [comment]
See: https://github.com/mbleigh/acts-as-taggable-on/pull/872

**Comment by rgbskills** [comment]
I am removing Acts as taggable from my project and using something else, I think I will give "gutentag" gem a try. :(

**Comment by kobaltz** [comment]
@rgbskills I feel the same way. However, on a Rails 5.2 app, I was able to get around this with a private method in the controller just to get things working again temporarily.

It basically gets the list of removed tags and removes them from the model. It then gets the new tags and adds them to the model. I ran into similar issues with the `[]=` error and the other reported ones. This seems to get around the problem without having to change any other code. For existing applications, this may be a better workaround than migrating to a different solution.

```
  def set_tags
    new_tags = model_strong_params['tag_list'].to_a.reject { |c| c.empty? }
    old_tags = @model.tags.map(&:name)
    return if new_tags == old_tags
    (old_tags - new_tags).map {|e| @model.tag_list.remove(e)}
    (new_tags - old_tags ).map {|e| @model.tag_list.add e}
  end
```

**Comment by noma4i** [comment]
I have merged all knowing fixes into one fork. Feel free to use/fork it https://github.com/noma4i/acts-as-taggable-on

**Comment by glendel** [comment]
Please go to here : [Pull Request #887](https://github.com/mbleigh/acts-as-taggable-on/pull/887) to see all the ready to merge and to use solutions to work with Rails 5.2! It is fully tested and ready to go! It is just missing to merge the changes into the main project!
