### ISSUE TITLE
How to use model callback methods?

### ISSUE THREAD

**Issue by ccoeder** [mbleigh/acts-as-taggable-on#918]
Hi,

I want to broadcast **most used tags** so I think I need something like `after_save` or `after_create_commit` how can I achieve this?

act-as-taggable model

`self.tag_list.add(self.reason.scan(/#(\w+)/).flatten.uniq) unless self.reason.nil?`

and my tag model inherits from act-as-taggable

```
class Tag < ActsAsTaggableOn::Tag
  after_save do
    puts "It should come here but it's not working"
  end
end
```

Thanks.

**Comment by stevendaniels** [comment]
Hi @ccoeder,

The issue you're facing is that the model you are using is adding tags to the `ActsAsTaggableOn::Tag` model, not the `Tag` model that you created. If you wanted to use callbacks you should try something like this: 

```ruby
class ActsAsTaggableOn::Tag
  after_save do
    puts "It should come here; it's working now"
  end
end

# generated with `rails g model User reason:string`
class User < ActiveRecord::Base
  acts_as_taggable
  def update_reason(reason)
    self.reason = reason
    self.tag_list.add(self.reason.scan(/#(\w+)/).flatten.uniq) unless self.reason.nil?

    reason
  end
end
```

```ruby
# disable logging so that we can see the message
ActiveRecord::Base.logger = nil 

user = User.new
user.update_reason "#2"
user.save #=> "It should come here; it's working now"
```

In the future, questions like this are probably better addressed on sites like [StackOverflow](http://stackoverflow.com). 

This issue can be closed.

**Comment by ccoeder** [comment]
Thank you!

**Comment by stoplion** [comment]
This is not working for me. Where should this file be located?
`Model/ActsAsTaggableOn/Tag` ?
or `Model/Tag`
