### ISSUE TITLE
How to get *ALL* tags on an object regardless of its contexts

### ISSUE THREAD

**Issue by syedrakib** [mbleigh/acts-as-taggable-on#919]
I have a `my_car` instance of a `Car` class. I have many taggings on it on `wheel` context, on `body` context, on `interior` context, and some general tags on `tags` context. 

While i am able to `my_car.tags_list`, `my_car.wheel_list`, `my_car.body_list`, `my_car.interior_list`, i am not able to do something like `my_car.all_tags` so that i can see **ALL** the tags on the `my_car` object regardless of their tagging contexts.

How do i do that?

**Comment by stevendaniels** [comment]
Hi @syedrakib,

You can get a list of all tags by using: `my_car.taggings`. This includes tags for all scopes for the model.

In the future, questions like this are probably better addressed on sites like [StackOverflow](http://stackoverflow.com).

This issue can be closed.

**Comment by syedrakib** [comment]
That is giving me all `taggings`... but not all `tags`. For tags, have to do re-map with `.taggings.map(&:tag)`. Was wondering if there was a lesser cumbersome way to do this than that. Thanks for the response.

**Comment by syedrakib** [comment]
[Stackoverflow](https://stackoverflow.com/a/52212911/636762) suggested `.base_tags` as a way
