### ISSUE TITLE
DEPRECATION WARNING: ActiveSupport::Multibyte::Unicode#downcase is deprecated and will be removed from Rails 6.1

### ISSUE THREAD

**Issue by tirdadc** [mbleigh/acts-as-taggable-on#938]
acts-as-taggable-on 5.0
rails 6.0.0.beta1

Running specs that involve tags results in this deprecation notice:

`DEPRECATION WARNING: ActiveSupport::Multibyte::Unicode#downcase is deprecated and will be removed from Rails 6.1. Use String methods directly.`

**Comment by robinsingh-bw** [comment]
Any news on this?

**Comment by yisselda** [comment]
Will this get updated?

**Comment by cheeseweasel** [comment]
@yisselda It was resolved in https://github.com/mbleigh/acts-as-taggable-on/commit/950c01072b7ab6227d74dc0d0b112f0135281fc2

@seuros, this issue can be closed.
