### ISSUE TITLE
Runtime dependency on activerecord (~> 5.0) makes gem incompatible with Rails 6.0.0.rc1

### ISSUE THREAD

**Issue by crwhitesides** [mbleigh/acts-as-taggable-on#953]
This issue is in the same vein as #944, but I figured I'd bring it up since I am using the latest version of Rails (6.0.0.rc1) and bundler is reporting an incompatibility: 

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    acts-as-taggable-on (~> 6.0) was resolved to 6.0.0, which depends on
      activerecord (~> 5.0)

    rails (~> 6.0.0.rc1) was resolved to 6.0.0.rc1, which depends on
      activerecord (= 6.0.0.rc1)
```

**Comment by raviy06** [comment]
Try pointing the gem to master branch.

**Comment by TheTeaNerd** [comment]
Now that Rails 6 is released, this also blocks using this Gem with a Rails 6 application. 

Support is on `master` though.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be great to release a new version though!
