### ISSUE TITLE
Installation not working on Rails 6.0 stable

### ISSUE THREAD

**Issue by tolesco** [mbleigh/acts-as-taggable-on#961]
I'm getting an error when I try to install it with Rails 6.0.0 stable.

With `gem 'acts-as-taggable-on', '~> 6.0'` on the Gemfile I get this error:

<img width="1263" alt="Screen Shot 2019-08-20 at 12 27 06 AM" src="https://user-images.githubusercontent.com/4991205/63320183-7dc57200-c2e2-11e9-8a98-a8f76259587d.png">

I fixed changing to this line in the Gemfile: 

`gem 'acts-as-taggable-on', git: 'https://github.com/mbleigh/acts-as-taggable-on'`

And I get the output:

`Using acts-as-taggable-on 6.0.1 (was 5.0.0) from https://github.com/mbleigh/acts-as-taggable-on (at master@fbf2b60)`. 

Bundle completed, no error present.

Any idea of why is this occurring? It's safe to use 6.0.1 in production?

**Comment by sandergroen** [comment]
@tolesco you installed the gem from the master branch which is in development. So I would not recommend using that in production I think you could better wait for version 6.1 to be released.
I would like to upgrade the project I'm currently working on to Rails version 6.0 so I hope version 6.1 will be released soon.

**Comment by tolesco** [comment]
@sandergroen thanks for the tip, I'll wait for version 6.1 as you told me: D

**Comment by mayeco** [comment]
ping @mbleigh

**Comment by easybills-admin** [comment]
Any news on this?

**Comment by engwan** [comment]
@seuros I see that the PR has been merged. Is there a plan to publish the release to rubygems soon? Thanks!
