### ISSUE TITLE
strict_case_match doesn't work as expected

### ISSUE THREAD

**Issue by endorfin** [mbleigh/acts-as-taggable-on#965]
As I noticed today, the option **ActsAsTaggableOn.strict_case_match = true** only works for creating new tags, but not with the **tagged_with** scope.

After a little research I found out that the third parameter _case_sensitive_ for **matches** and **matches_any** in query_base.rb (tag_match_type, tags_match_type) isn't set.

So there is always a search with ILIKE.

**Comment by endorfin** [comment]
pull request #966

**Comment by nbulaj** [comment]
This one could be closed now I think as #966 merged

**Comment by endorfin** [comment]
Thanks!
