### ISSUE TITLE
There are no tracking for changes in version 6.5.0

### ISSUE THREAD

**Issue by wenderjean** [mbleigh/acts-as-taggable-on#974]
I couldn't find in `CHANGELOG` or even in the release notes the changes present in version 6.5.0, there is another place I could look at?

**Comment by seuros** [comment]
Can you open a PR with the changes ? 
Else i will do that in few days.

**Comment by valscion** [comment]
Seems like https://github.com/mbleigh/acts-as-taggable-on/pull/980 resolved this issue :relaxed:

**Comment by wenderjean** [comment]
You're right @valscion, I'm good to close this issue. :)
