### ISSUE TITLE
Removing this gem breaks the migrations

### ISSUE THREAD

**Issue by timwis** [mbleigh/acts-as-taggable-on#996]
Because the migrations reference class properties to determine the table name, `rails db:migrate` no longer works when you remove acts-as-taggable-on from your Gemfile. Is there some other way to uninstall this gem?

**Comment by fnguyen-tc** [comment]
Remove the migration files with the Gem

**Comment by silva96** [comment]
you should not be doing "db:migrate" to set up new environments, use db:schema:load for that purpose, is faster and less error prone. Migrations are for incremental updates, for production and your co-workers local machines that have been upgrading one migration at the time.
